version: "3.12"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: library_service
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  web:
    build:
      context: .
    command: gunicorn Library_service.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DEBUG: "True"
      DJANGO_SETTINGS_MODULE: Library_service_project.settings
      DATABASE_URL: postgres://postgres:postgres@db:5432/library_service_project
    depends_on:
      - db
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network: