# Generated by Django 5.1.3 on 2024-12-13 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("book", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Borrowing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("borrow_date", models.DateField(verbose_name="borrow_date")),
                (
                    "expected_return_date",
                    models.DateField(verbose_name="expected_return_date"),
                ),
                (
                    "actual_return_date",
                    models.DateField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Actual Return Date",
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="book.book"
                    ),
                ),
            ],
        ),
    ]
