# Generated by Django 5.1.3 on 2024-12-07 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("borrowing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowing",
            name="actual_return_date",
            field=models.DateField(
                blank=True, default=None, null=True, verbose_name="Actual Return Date"
            ),
        ),
    ]
